{% set version = "2.0.1.14" %}

package:
  name: r-gdalutils
  version: {{ version }}

source:
  fn: gdalUtils_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gdalUtils_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gdalUtils/gdalUtils_{{ version }}.tar.gz
  sha256: 890a502b2eb5f1b23655fab94caad5d32adca05b93f5db1d96d9dcde3f0e7737

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r.utils
    - r-foreach
    - r-raster
    - r-rgdal
    - r-sp
  run:
    - r-base
    - r-r.utils
    - r-foreach
    - r-raster
    - r-rgdal
    - r-sp

test:
  commands:
    - $R -e "library('gdalUtils')"  # [not win]
    - "\"%R%\" -e \"library('gdalUtils')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gdalUtils
  license: GPL (>= 2)
  summary: Wrappers for the Geospatial Data Abstraction Library (GDAL) Utilities.

extra:
  recipe-maintainers:
    - ocefpaf
