{% set version = '2.0.1.14' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gdalutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdalUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdalUtils/gdalUtils_{{ version }}.tar.gz
  sha256: 890a502b2eb5f1b23655fab94caad5d32adca05b93f5db1d96d9dcde3f0e7737

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r.utils
    - r-foreach
    - r-raster
    - r-rgdal
    - r-sp
  run:
    - r-base
    - r-r.utils
    - r-foreach
    - r-raster
    - r-rgdal
    - r-sp

test:
  commands:
    - $R -e "library('gdalUtils')"           # [not win]
    - "\"%R%\" -e \"library('gdalUtils')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gdalUtils
  license: GPL (>= 2)
  summary: Wrappers for the Geospatial Data Abstraction Library (GDAL) Utilities.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gdalUtils
# Maintainer: Jonathan Asher Greenberg <gdalUtils@estarcion.net>
# License: GPL (>= 2)
# Title: Wrappers for the Geospatial Data Abstraction Library (GDAL) Utilities
# Type: Package
# LazyLoad: yes
# Author: Jonathan Asher Greenberg and Matteo Mattiuzzi
# Description: Wrappers for the Geospatial Data Abstraction Library (GDAL) Utilities.
# Version: 2.0.1.14
# Date: 2018-04-22
# Depends: R (>= 2.14.0)
# Imports: sp, foreach, R.utils, raster, rgdal
# SystemRequirements: GDAL binaries
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-22 23:09:51 UTC; jgrn307
# Repository: CRAN
# Date/Publication: 2018-04-23 03:23:04 UTC
