# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "k52EPapuohwMPrHRtQZaf+QVVUz8PJLLxlhIAIwNtbRA9egNk3SQdvcNExcK0lhWyhP3VAO8C6gcRQ9MvlWUeLSzJ2bubUcdCWNYx0NGkNZ6nDCbEtv3QoJYtzlJnAUbffOs1Phjx9uAXyCSVfkWo9PULLVK0VXRXDtic0sfldfapoamkRWrSPgljviZkC9n+oPwO8ZHYg4jhh0Nb3ojIa8O2jNtj4OyMQY93Lyxe8TO6J3kHC+j8c3IHx0oy9wkDqio50x5j3GxBa+8IOFvyXEUCflRvouVxt01+gU8UKwtOaj56sppn6HqkjHrtffhMaj5RmuHHUB04j63GmUAZbBoFYl911hmmDEeb/9DSHkB/RpMWu/HbDjZ1cjcN99jrLqU0maezB2OlP6anNVnDqxa+MnnHPfmNl+rapAKfqrE82HiC7CmBmCxZm5CIJ/n2sij9wi/GxBzFM6yl0JfY30DcMwK9mGHqEizUvA7WkTlWU5bwJew6VZoKN65cCjEIKi4NjR4lrCPfCLtxCvZAtuCpbdidh/X8zEOgpbf86Eg/ztF+jL3TQ7CKeTw1W5s5ZYJiv2GoJUq+TvmuPyyO/2t8YuCRHAmRFndwwDN2BXqzga5G6fv2KWEwDDnILQnHv6OOfC6ZGCRUsDuh5SHyBPeyKkYz4vzvzwSuTste0U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
